"""
Purpose:
- Executes generated bytecode with a stack-based virtual machine.
- VM instruction execution will be implemented in Prompt 10.
"""

import json
from dataclasses import dataclass, field
from typing import Any, Dict, List, Tuple


class VMError(Exception):
    """Raised for invalid VM instructions or runtime stack issues."""


@dataclass
class StackVM:
    """
    Stack-based virtual machine for language bytecode.

    Step-by-step execution model:
    1. Read next instruction by program counter (PC).
    2. Decode opcode + optional argument.
    3. Mutate stack/store/output according to opcode semantics.
    4. Advance PC, or jump to a label for control flow.
    5. Repeat until PC exits instruction list.
    """

    stack: List[Any] = field(default_factory=list)
    return_stack: List[int] = field(default_factory=list)
    variables: Dict[str, Any] = field(default_factory=dict)
    output: List[str] = field(default_factory=list)
    pc: int = 0
    labels: Dict[str, int] = field(default_factory=dict)

    def run(self, instructions: List[str]) -> Dict[str, object]:
        """Execute bytecode and return structured VM result."""
        self._reset_runtime()
        self.labels = self._index_labels(instructions)

        while self.pc < len(instructions):
            raw_line = instructions[self.pc].strip()
            if not raw_line:
                self.pc += 1
                continue

            opcode, argument = self._parse_instruction(raw_line)
            self._execute(opcode, argument)

        return {
            "success": True,
            "variables": self.variables,
            "output": self.output,
            "stack": self.stack,
        }

    def _reset_runtime(self) -> None:
        self.stack.clear()
        self.return_stack.clear()
        self.variables.clear()
        self.output.clear()
        self.pc = 0
        self.labels.clear()

    def _index_labels(self, instructions: List[str]) -> Dict[str, int]:
        labels: Dict[str, int] = {}
        for index, line in enumerate(instructions):
            stripped = line.strip()
            if stripped.startswith("LABEL "):
                label_name = stripped.split(maxsplit=1)[1]
                labels[label_name] = index
        return labels

    def _parse_instruction(self, line: str) -> Tuple[str, str]:
        parts = line.split(maxsplit=1)
        if len(parts) == 1:
            return parts[0], ""
        return parts[0], parts[1]

    def _execute(self, opcode: str, argument: str) -> None:
        # Required Prompt 10 opcodes
        if opcode == "PUSH":
            self.stack.append(self._to_number(argument))
            self.pc += 1
            return
        if opcode == "ADD":
            right = self._pop_stack("ADD")
            left = self._pop_stack("ADD")
            self.stack.append(left + right)
            self.pc += 1
            return
        if opcode == "STORE":
            value = self._pop_stack("STORE")
            self.variables[argument] = value
            self.pc += 1
            return
        if opcode == "PRINT":
            value = self._pop_stack("PRINT")
            self.output.append(self._format_output(value))
            self.pc += 1
            return

        if opcode == "CALL":
            self.return_stack.append(self.pc + 1)
            self.pc = self._label_to_pc(argument)
            return
        if opcode == "RETURN":
            if not self.return_stack:
                raise VMError("RETURN without matching CALL.")
            val = self.stack.pop() if self.stack else 0.0
            self.pc = self.return_stack.pop()
            self.stack.append(val)
            return
        if opcode == "DROP":
            self._pop_stack("DROP")
            self.pc += 1
            return

        # Compatibility opcodes generated by current codegen stage.
        if opcode == "LOAD_CONST":
            raw = argument.strip()
            if raw.startswith('"') and raw.endswith('"'):
                try:
                    self.stack.append(json.loads(raw))
                except json.JSONDecodeError as exc:
                    raise VMError(f"Bad string literal: {raw!r}") from exc
            else:
                self.stack.append(self._to_number(raw))
            self.pc += 1
            return
        if opcode == "LOAD_VAR":
            if argument not in self.variables:
                raise VMError(f"Undefined variable read: '{argument}'.")
            self.stack.append(self.variables[argument])
            self.pc += 1
            return
        if opcode in {"SUB", "MUL", "DIV", "CMP_EQ", "CMP_NE", "CMP_LT", "CMP_LE", "CMP_GT", "CMP_GE"}:
            self._execute_binary(opcode)
            self.pc += 1
            return
        if opcode == "JUMP":
            self.pc = self._label_to_pc(argument)
            return
        if opcode == "JUMP_IF_FALSE":
            condition = self._pop_stack("JUMP_IF_FALSE")
            if isinstance(condition, str):
                raise VMError("JUMP_IF_FALSE expects a numeric condition.")
            if condition == 0:
                self.pc = self._label_to_pc(argument)
            else:
                self.pc += 1
            return
        if opcode == "LABEL":
            # LABEL is a marker; execution just advances.
            self.pc += 1
            return

        raise VMError(f"Unknown opcode '{opcode}' at PC {self.pc}.")

    def _execute_binary(self, opcode: str) -> None:
        right = self._pop_stack(opcode)
        left = self._pop_stack(opcode)
        if isinstance(left, str) or isinstance(right, str):
            raise VMError(f"Opcode '{opcode}' does not support string operands.")

        if opcode == "SUB":
            self.stack.append(left - right)
            return
        if opcode == "MUL":
            self.stack.append(left * right)
            return
        if opcode == "DIV":
            self.stack.append(left / right)
            return
        if opcode == "CMP_EQ":
            self.stack.append(1.0 if left == right else 0.0)
            return
        if opcode == "CMP_NE":
            self.stack.append(1.0 if left != right else 0.0)
            return
        if opcode == "CMP_LT":
            self.stack.append(1.0 if left < right else 0.0)
            return
        if opcode == "CMP_LE":
            self.stack.append(1.0 if left <= right else 0.0)
            return
        if opcode == "CMP_GT":
            self.stack.append(1.0 if left > right else 0.0)
            return
        if opcode == "CMP_GE":
            self.stack.append(1.0 if left >= right else 0.0)
            return

    def _label_to_pc(self, label: str) -> int:
        if label not in self.labels:
            raise VMError(f"Unknown jump label '{label}'.")
        return self.labels[label]

    def _pop_stack(self, opcode: str) -> Any:
        if not self.stack:
            raise VMError(f"Stack underflow while executing '{opcode}'.")
        return self.stack.pop()

    def _format_output(self, value: object) -> str:
        if isinstance(value, str):
            return value
        return str(self._normalize_number(float(value)))

    def _to_number(self, text: str) -> float:
        try:
            return float(text)
        except ValueError as exc:
            raise VMError(f"Expected numeric literal, got '{text}'.") from exc

    def _normalize_number(self, value: float) -> float:
        return int(value) if float(value).is_integer() else value


def run_bytecode(instructions: List[str]) -> Dict[str, object]:
    """Convenience wrapper for running bytecode on the stack VM."""
    return StackVM().run(instructions)
